PCIe D05 auto scripts

diff --git a/config/common_lib b/config/common_lib
--- a/config/common_lib
+++ b/config/common_lib
@@ -69,3 +69,269 @@ function setTrustRelation
     return 0
 }
 
+####################################################################################
+#add by hezhongyan
+##################
+#Alone Functions
+OutLog()
+{
+    local nStatus=${1}
+    local sStatus=${2}
+    local sMsg=${3}
+    local flLog=${4:-/dev/null}
+    local bExitErr=${5:-false}
+
+    local sLogA
+    case "${nStatus}" in
+    0)
+        sStatus=${sStatus:-Info}
+        sLogA=$(printf "%s[%3d]%s[%3d]%5s[${nStatus}]: %s" "${FUNCNAME[1]}" "${BASH_LINENO[0]}" "${FUNCNAME[0]}" ${LINENO} "${sStatus}" "${sMsg}")
+        echo "${sLogA}"
+        echo "${sLogA}" >> "${flLog}"
+        ;;
+    *)
+        sStatus=${sStatus:-Error}
+        sLogA=$(printf "%s[%3d]%s[%3d]%5s[${nStatus}]: %s" "${FUNCNAME[1]}" "${BASH_LINENO[0]}" "${FUNCNAME[0]}" ${LINENO} "${sStatus}" "${sMsg}")
+        echo "${sLogA}" 1>&2
+        echo "${sLogA}" >> "${flLog}"
+        if [ "${bExitErr}" == "true" ]; then
+            exit ${nStatus}
+        fi
+        ;;
+    esac
+}
+export -f OutLog
+
+LoadSourceFileParent()
+{
+    local drCur1=${1}
+    local flFind1=${2}
+    local varPaths=${3}
+    local flLog=${4}
+    local bExitErr=${5:-true}
+
+    if [ -z "${drCur1}" -o -z "${flFind1}" ]; then
+        g_sErrCur="directory or file name is empty"
+        eval ${varPaths}=
+        return
+    fi
+
+    local flPub1 s1 s2 s3
+    flPub1=${drCur1}/${flFind1}
+    if [ ! -f "${flPub1}" ]; then
+        s1=$(find ${drCur1}/.. ${g_argFindMaxDepth} -type f -name "${flFind1}")
+        if [ -z "${s1}" ]; then
+            g_sErrCur="Not found ${flFind1}"
+            OutLog 1 "Error" "${g_sErrCur}" "${flLog}" ${bExitErr}
+        fi
+        flPub1=${s1}
+    fi
+    eval ${varPaths}=\${flPub1}
+}
+export -f LoadSourceFileParent
+
+##########
+#Complex Functions
+RunTable()
+{
+    local flTableOrigin=${1}
+    local flTableStatus=${2}
+    local drScript=${3}
+    local flLog=${4:-/dev/null}
+
+    local sPass
+    sPass=$(echo "${g_statusPass}" |sed 's#\([]/*[]\)#\\\1#g')
+
+    local sStatusTable
+    sStatusTable=
+    if [ -f "${flTableStatus}" ]; then
+        if [ "${g_bTCsReset}" == "true" ]; then
+            rm -f "${flTableStatus}"
+        else
+            sStatusTable=$(cat "${flTableStatus}")
+        fi
+    fi
+
+    local sR0 sR1 sLevelR1 sLevelR2 sTTitle1 sTTitle2 sScript1 sScript2 sFuncNa
+    local sStatus1 nRt1 bRun1 sLineStatus
+    while read sR0; do
+        sR1=$(echo "${sR0}" |sed "s/^[ \t]\+//;s/[ \t\r]\+\$//")
+        if [ -z "${sR1}" ]; then
+            continue
+        fi
+
+        sLevelR1=$(awk -F'\t' '{print $8}' <<< "${sR1}" |sed "s/^[ \t]\+//;s/[ \t]+\$//")
+        sLevelR2=$(sed 's#\([]/*[]\)#\\\1#g' <<< "${sLevelR1}")
+        sTTitle1=$(awk -F'\t' '{print $5}' <<< "${sR1}" |sed "s/^[ \t]\+//;s/[ \t]+\$//")
+        sTTitle2=$(sed 's#\([]/*[]\)#\\\1#g' <<< "${sTTitle1}")
+        sScript1=$(awk -F'\t' '{print $6}' <<< "${sR1}" |sed "s/^[ \t]\+//;s/[ \t]+\$//")
+        sFuncNa=$(awk -F'\t' '{print $7}' <<< "${sR1}" |sed "s/^[ \t]\+//;s/[ \t]+\$//")
+
+        g_sErrCur=
+        grep -q "^${sLevelR2}\$" <<< "${g_sLevelRun}"
+        if [ $? -ne 0 ]; then
+            g_sErrCur="test case close"
+            sStatus1=${g_statusClose}
+        else
+            nRt1=${g_nNone}
+            bRun1=true
+            if [ -n "${sScript1}" ]; then
+                LoadSourceFileParent "${drScript}" "${sScript1}" sScript2 "${flLog}" false
+                if [ -n "${sScript2}" ]; then
+                    . "${sScript2}"
+                    if [ $? -ne 0 ]; then
+                        nRt1=${g_nBlock}
+                        g_sErrCur="environment not OK"
+                    fi
+                else
+                    bRun1=false
+                    g_sErrCur="${sScript1} not exist"
+                fi
+            fi
+
+            if ${bRun1}; then
+                if [ -n "${sFuncNa}" ]; then
+                    ${sFuncNa}
+                    nRt1=$?
+                else
+                    g_sErrCur="function is empty"
+                fi
+            fi
+
+            case ${nRt1} in
+            ${g_nPass})
+                sStatus1=${g_statusPass}
+                ;;
+            ${g_nFail})
+                sStatus1=${g_statusFail}
+                ;;
+            ${g_nBlock})
+                sStatus1=${g_statusBlock}
+                ;;
+            ${g_nNone})
+                sStatus1=${g_statusNone}
+                ;;
+            127)
+                g_sErrCur="${sFuncNa} not exist"
+                sStatus1=${g_statusNone}
+                ;;
+            *)
+                sStatus1=${g_statusUndef}
+                ;;
+            esac
+        fi
+
+        if [ -z "${sTTitle1}" ]; then
+            g_sErrCur="no title ${sR1}"
+            sLineStatus=
+        else
+            sLineStatus=$(grep "${sTTitle2}" <<< "${sStatusTable}")
+        fi
+        if [ -n "${sLineStatus}" ]; then
+            #更新状态表中这条用例的状态;
+            grep -q "^${sPass}${g_sSplit}" <<< "${sLineStatus}"
+            if [ $? -ne 0 ]; then
+                sStatusTable=$(sed "/${sTTitle2}/d" <<< "${sStatusTable}")
+                sStatusTable=${sStatusTable}$'\n'${sStatus1}${g_sSplit}${sTTitle1}${g_sSplit}${g_sErrCur}
+            fi
+        else
+            sStatusTable=${sStatusTable}$'\n'${sStatus1}${g_sSplit}${sTTitle1}${g_sSplit}${g_sErrCur}
+        fi
+    done < "${flTableOrigin}"
+
+    echo "${sStatusTable}" > "${flTableStatus}"
+}
+export -f RunTable
+
+GenReport()
+{
+    local flTableOrigin=${1}
+    local flTableStatus=${2}
+    local sModule=${3}
+    local flLog=${4:-/dev/null}
+
+    local sPass sFail sStatus1 sSearch1 sSearch2 sMessage 
+    sPass=$(echo "${g_statusPass}" |sed 's#\([]/*[]\)#\\\1#g')
+    sFail=$(echo "${g_statusFail}" |sed 's#\([]/*[]\)#\\\1#g')
+
+    if [ ! -f "${flTableStatus}" ]; then
+        OutLog 1 "" "${flTableStatus} not exist." "${flLog}" true
+    fi
+
+    sTableOrigin=$(cat "${flTableOrigin}")
+
+    local Module_Name JIRA_ID Designed_Requirement_ID Test_Case_ID Test_Item Test_Case_Title
+    Module_Name=${sModule}
+    while read sR0; do
+        sR1=$(echo "${sR0}" |sed "s/^[ \t]\+//;s/[ \t\r]\+\$//")
+        if [ -z "${sR1}" ]; then
+            continue
+        fi
+
+        sStatus1=$(echo "${sR1}" |awk -F'\t' '{print $1}')
+        sSearch1=$(echo "${sR1}" |awk -F'\t' '{print $2}')
+        sSearch2=$(sed 's#\([]/*[]\)#\\\1#g' <<< "${sSearch1}")
+        sMessage=$(echo "${sR1}" |awk -F'\t' '{print $3}')
+        sTCLine1=$(grep -i "${sSearch2}" <<< "${sTableOrigin}" |sed "s/\r\+//g")
+        if [ -n "${sTCLine1}" ]; then
+            JIRA_ID=$(echo "${sTCLine1}" |awk -F'\t' '{print $1}')
+            Designed_Requirement_ID=$(echo "${sTCLine1}" |awk -F'\t' '{print $2}')
+            Test_Case_ID=$(echo "${sTCLine1}" |awk -F'\t' '{print $3}')
+            Test_Item=$(echo "${sTCLine1}" |awk -F'\t' '{print $4}')
+            Test_Case_Title=$(echo "${sTCLine1}" |awk -F'\t' '{print $5}')
+            echo "${sStatus1}" |grep -q "^${sPass}\$"
+            if [ $? -eq 0 ]; then
+                writePass
+            else
+                echo "${sStatus1}" |grep -q "^${sFail}\$"
+                if [ $? -eq 0 ]; then
+                    writeFail "${sMessage}"
+                fi
+            fi
+        fi
+    done < "${flTableStatus}"
+}
+export -f GenReport
+
+GenTable()
+{
+    local flTableStatus=${1}
+    local flTableOutput=${2}
+    local sModule=${3}
+    local flLog=${4:-/dev/null}
+
+    local sPass sFail sStatus1 sSearch1 sSearch2 sMessage 
+    sPass=$(echo "${g_statusPass}" |sed 's#\([]/*[]\)#\\\1#g')
+    sFail=$(echo "${g_statusFail}" |sed 's#\([]/*[]\)#\\\1#g')
+
+    if [ ! -f "${flTableStatus}" ]; then
+        OutLog 1 "" "${flTableStatus} not exist." "${flLog}" true
+    fi
+
+    local sTCsTable
+    sTCsTable=$(cat "${g_flTCsTable}")${g__n}
+
+    while read sR0; do
+        sR1=$(echo "${sR0}" |sed "s/^[ \t]\+//;s/[ \t\r]\+\$//")
+        if [ -z "${sR1}" ]; then
+            continue
+        fi
+
+        sStatus1=$(echo "${sR1}" |awk -F'\t' '{print $1}')
+        sSearch1=$(echo "${sR1}" |awk -F'\t' '{print $2}')
+        sSearch2=$(sed 's#\([]/*[]\)#\\\1#g' <<< "${sSearch1}")
+        sTCLine1=$(grep -i "${sSearch2}" "${g_flTCsTable}" |sed "s/\r\+//g")
+        if [ -n "${sTCLine1}" ]; then
+            sTCsTable=$(echo "${sTCsTable}" |sed "/${sSearch2}/s/^/${sStatus1}${g_sSplit}/")
+        else
+            sStatus1=${g_statusNone}
+            sTCsTable=$(echo "${sTCsTable}" |sed "\${a ${sStatus1}${g_sSplit}${sSearch1}${g__n}q};")
+        fi
+    done < "${flTableStatus}"
+
+    echo "${sTCsTable}" > "${flTableOutput}"
+}
+export -f GenTable
+
+####################################################################################
+
diff --git a/pcie_autotest/config/pcie_test_lib b/pcie_autotest/config/pcie_test_lib
--- a/pcie_autotest/config/pcie_test_lib
+++ b/pcie_autotest/config/pcie_test_lib
@@ -7,8 +7,8 @@ cd "${g_dpCur}" >/dev/null
 g_dpCur=${PWD}
 cd "${drCur0}" >/dev/null
 g_pfnCur=${g_dpCur}/${g_fnCur}
-export g_fn_testcase_common=${g_fnCur}
-export g_dp_testcase_common=${g_dpCur}
+export g_fn_pcie_test_common=${g_fnCur}
+export g_dp_pcie_test_common=${g_dpCur}
 
 #####################
 #check load from command line
@@ -31,38 +31,33 @@ fi
 export g_defSourceFiles=${g_defSourceFiles}$'\n'${g_pfnCur}
 printf "%s[%3d]%5s: Load [${g_pfnCur}] call by [${g_flParent}]\n" "${FUNCNAME[0]}" ${LINENO} "Info"
 
-#####################
+####################################################################################
 #Load Public functions
-drCur1=${g_dp_testcase_common}
+drCur1=${g_dp_pcie_test_common}
 fsrc1=funcs.common
 flPub1=${drCur1}/${fsrc1}
 if [ ! -f "${flPub1}" ]; then
-    s1=$(find ${drCur1}/.. -type f -name "${fsrc1}")
-    if [ -z "${s1}" ]; then
-        s1=$(find ${drCur1}/../.. -type f -name "${fsrc1}")
-        if [ -z "${s1}" ]; then
-            printf "%s[%3d]%5s: Not found ${fsrc1}\n" "${FUNCNAME[0]}" ${LINENO} "Error" >&2
-            exit 1
-        fi
-    fi
+    s1=$(find ${drCur1}/.. ${g_argFindMaxDepth} -type f -name "${fsrc1}")
+    #if [ -z "${s1}" ]; then
+    #    printf "%s[%3d]%5s: Not found ${fsrc1}\n" "${FUNCNAME[0]}" ${LINENO} "Error" >&2
+    #    exit 1
+    #fi
     flPub1=${s1}
 fi
-$(sed "s#^#. #" <<< "${flPub1}")
+if [ -n "${flPub1}" ]; then
+    $(sed "s#^#. #" <<< "${flPub1}")
+fi
 
 #####################
 #Load config
-flLoad1=${g_fn_testcase_common%%.*}.cfg
-LoadSourceFileParent "${g_dp_testcase_common}" "${flLoad1}" flPath1 true
+LoadSourceFileParent "${g_dp_pcie_test_common}" "${g_fn_pcie_test_common%_*}_config" flPath1 "${g_flLog}" true
 $(sed "s#^#. #" <<< "${flPath1}")
-
-LoadSourceFileParent "${g_dp_testcase_common}" "${g_flTCsList}" g_flTCsList true
-LoadSourceFileParent "${g_dp_testcase_common}" "${g_flTCRun}" g_flTCRun true
 
 #####################
 #init
-export g_flList=$(echo "${g_flList}" |sed "/^[ \t]*#/d;/^[ \t]*\$/d;s@^[ \t]\+@@;s@[ \t]\+\$@@")
+#export g_flList=$(sed "/^[ \t]*\$/d;/^[ \t]*#/d;s/^[ \t]\+//;s/[ \t]\+\$//" <<< "${g_flList}")
 
-export g_flBaseLog=${g_drTmp}/${g_fn_testcase_common%%.*}
+export g_flBaseLog=${g_drTmp}/${g_fn_pcie_test_common%_*}
 if [ -d "${g_flBaseLog}_bak" ]; then
     rm -rf "${g_flBaseLog}_bak"
 fi
@@ -75,21 +70,67 @@ if [ -n "${sList}" ]; then
 fi
 
 ###########
+export g_sLevelRun=$(sed "/^[ \t]*\$/d;/^[ \t]*#/d;s@^[ \t]\+@@;s@[ \t]\+\$@@" <<< "${g_sLevelRun}")
 export g_sErrCur=
 
 #####################
 #Alone Functions
-CmdACPI()
+ArgInCmdLine()
 {
-    grep -q " acpi=force " /proc/cmdline
+    local sKey1=${1}
+
+    grep -q "\(^\| \)${sKey1}\( \|\$\)" /proc/cmdline
     if [ $? -ne 0 ]; then
-        g_sErrCur="not have acpi=force in cmdline"
+        g_sErrCur="not have ${sKey1} in cmdline"
+        OutLog 1 "" "${g_sErrCur}." "${g_flLog}" false
+        return 1
+    fi
+}
+
+LspcikKeysiBA()
+{
+    local sKey1=${1}
+    local bIC=${2:-false}
+    local nB=${3:-0}
+    local nA=${4:-0}
+
+    local argic
+    argic=
+    if [ "${bIC}" == "true" ]; then
+        argic=-i
+    fi
+    lspci -k |grep ${argic} -B${nB} -A${nA} -q "${sKey1}"
+    if [ $? -ne 0 ]; then
+        g_sErrCur="not have ${sKey1}"
         printf "%s[%3d]%5s: ${g_sErrCur}\n" "${FUNCNAME[0]}" ${LINENO} "Error" >> "${g_flLog}"
         return 1
     fi
-    return 0
 }
-export -f CmdACPI
+export -f LspcikKeysiBA
+
+DmesgCard2KeyBA()
+{
+    local sKey1=${1}
+    local sKey2=${2}
+    local nB=${3:-0}
+    local nA=${4:-0}
+
+    local bdfA
+    bdfA=$(lspci -k |grep -i -B${nB} -A${nA} "${sKey1}" |grep -o "^[0-9A-Fa-f:.]\+")
+    if [ -z "${bdfA}" ]; then
+        g_sErrCur="not have ${sKey1}"
+        printf "%s[%3d]%5s: ${g_sErrCur}\n" "${FUNCNAME[0]}" ${LINENO} "Error" >> "${g_flLog}"
+        return 1
+    fi
+
+    bdf1=$(echo "${bdfA}" |sed -n '1p')
+    dmesg |grep "${bdf1}" |grep -iq "${sKey2}"
+    if [ $? -ne 0 ]; then
+        g_sErrCur="not have ${sKey2}"
+        printf "%s[%3d]%5s: ${g_sErrCur}\n" "${FUNCNAME[0]}" ${LINENO} "Error" >> "${g_flLog}"
+        return 1
+    fi
+}
 
 CheckCard2KeysBA()
 {
@@ -113,8 +154,6 @@ CheckCard2KeysBA()
         printf "%s[%3d]%5s: ${g_sErrCur}\n" "${FUNCNAME[0]}" ${LINENO} "Error" >> "${g_flLog}"
         return 1
     fi
-
-    return 0
 }
 export -f CheckCard2KeysBA
 
@@ -140,10 +179,21 @@ DmesgCard2KeyBA()
         printf "%s[%3d]%5s: ${g_sErrCur}\n" "${FUNCNAME[0]}" ${LINENO} "Error" >> "${g_flLog}"
         return 1
     fi
-
-    return 0
 }
 export -f DmesgCard2KeyBA
+
+#条件:启动端(即服务端)为D03;
+ImageReuse()
+{
+    verD05=$(uname -r)
+    verD03=$(ssh root@${BACK_IP} 'uname -r')
+    if [ "${verD05}" != "${verD03}" ]; then
+        return 1
+    fi
+}
+
+#ECAM support for non-RC devices
+#dmesg |grep "ECAM"
 
 ##########
 #Complex Functions
@@ -161,112 +211,16 @@ ACPICard()
         return 1
     fi
 
-    CmdACPI
+    ArgInCmdLine "acpi=force"
 }
 export -f ACPICard
 
-CmdACPI82599()
-{
-    ACPICard 82599
-}
-export -f CmdACPI82599
-
-CmdACPIP3600()
-{
-    ACPICard "P3600 SSD" 1
-}
-export -f CmdACPIP3600
-
-CmdACPII350()
-{
-    ACPICard I350
-}
-export -f CmdACPII350
-
-MSIx82599()
-{
-    CheckCard2KeysBA 82599 "MSI-X: Enable+"
-}
-export -f MSIx82599
-
-MSIxP3600()
-{
-    CheckCard2KeysBA "P3600 SSD" "MSI-X: Enable+" 1
-}
-export -f MSIxP3600
-
-MSIxI350()
-{
-    CheckCard2KeysBA I350 "MSI-X: Enable+"
-}
-export -f MSIxI350
-
-Prefetch32b82599()
-{
-    DmesgCard2KeyBA "82599" 'BAR [0-9]\+: assigned \[mem [a-fxA-FX0-9-]\+ pref\]'
-}
-export -f Prefetch32b82599
-
-Prefetch64b82599()
-{
-    DmesgCard2KeyBA "82599" 'BAR [0-9]\+: assigned \[mem [a-fxA-FX0-9-]\+ 64bit pref\]'
-}
-export -f Prefetch64b82599
-
-Prefetch32bP3600()
-{
-    DmesgCard2KeyBA "P3600 SSD" 'BAR [0-9]\+: assigned \[mem [a-fxA-FX0-9-]\+ pref\]'
-}
-export -f Prefetch32bP3600
-
-Prefetch64bP3600()
-{
-    DmesgCard2KeyBA "P3600 SSD" 'BAR [0-9]\+: assigned \[mem [a-fxA-FX0-9-]\+ 64bit pref\]'
-}
-export -f Prefetch64bP3600
-
-Nonprefetch32bI350()
-{
-    DmesgCard2KeyBA "I350" 'BAR [0-9]\+: assigned \[mem [a-fxA-FX0-9-]\+\]'
-}
-export -f Nonprefetch32bI350
-
-Nonprefetch32bVGA()
-{
-    DmesgCard2KeyBA "VGA" 'BAR [0-9]\+: assigned \[mem [a-fxA-FX0-9-]\+\]'
-}
-export -f Nonprefetch32bVGA
-
-DoAll()
-{
-    local varDicKeys=${1}
-
-    local f_sTCsList sKs1 
-    eval sKs1=\${!${varDicKeys}[*]}
-    f_sTCsList=${g_flBaseLog}_${g_flStatusTable}
-    echo "${sKs1}" |grep -q "\(^\|[ ${g__t}]\)${g_sResetSymbol}\(\$\|[ ${g__t}]\)"
-    if [ $? -eq 0 ]; then
-        if [ -f "${f_sTCsList}" ]; then
-            rm -f "${f_sTCsList}"
-        fi
-    fi
-
-    local k1 s1 sStatus1 s2
-    for k1 in ${sKs1}; do
-        sStatus1=${g_statusFail}
-        g_sErrCur=
-        ${k1}
-        if [ $? -eq 0 ]; then
-            sStatus1=${g_statusPass}
-        fi
-        eval s1=\${${varDicKeys}[${k1}]}
-        echo "${sStatus1}${g_sSplit}${s1}${g_sSplit}${g_sErrCur}" >> "${f_sTCsList}"
-    done
-}
-export -f DoAll
-
 #####################
 #init2
+g_flTCsTable=$(basename "${g_flTCsTable}")
+LoadSourceFileParent "${g_dp_pcie_test_common}" "${g_flTCsTable}" g_flTCsTable "${g_flLog}" true
+
+g_flStatusTable=$(dirname "${g_flTCsTable}")/$(basename "${g_flStatusTable}")
 
 #####################
 
