Finish 62.5% of sas test

diff --git a/sas_autotest/config/sas_test_lib b/sas_autotest/config/sas_test_lib
--- a/sas_autotest/config/sas_test_lib
+++ b/sas_autotest/config/sas_test_lib
@@ -14,8 +14,19 @@ function test_case_function_run()
 {
     if [ x"${TEST_CASE_FUNCTION_SWITCH}" == x"on" ]
     then
-	echo "Begin to run script: "${exec_script}
+	echo "Begin to run testcase: "${TEST_CASE_TITLE}
         ${TEST_CASE_FUNCTION_NAME}
+
+        echo "The return value of script: "${exec_script}"is "$?
+        
+	if [ $? -ne 0 ]
+	then
+	    echo "The result of testcase "${TEST_CASE_TITLE}" is fail"
+            writeFail "SAS" "${TEST_CASE_TITLE}"
+        else
+	    echo "The result of testcase "${TEST_CASE_TITLE}" is success"
+            writePass "SAS" "${TEST_CASE_TITLE}"
+	fi
     else
         MESSAGE="BLOCK\tno automated use cases were implemented."
         echo "Skip the Scirpt: "${exec_script}
